on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.HUGO_PAT }}
          path: main
          submodules: true
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.140.2'
          extended: true
      - name: Build
        run: |
          cd main
          hugo mod init github.com/nulvox/gohugo-theme-ananke
          hugo --minify
      - name: Checkout pages
        uses: actions/checkout@v4
        with:
          repository: brokengadgets/brokengadgets.github.io
          token: ${{ secrets.HUGO_PAT }}
          path: pages
      - name: copy and deploy
        run: |
          cd pages
          date > generated.txt
          rm -rf images/*
          cp -pr ../main/public/* .
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "generated by hugo runner for commit $GITHUB_SHA"
          git push
